# Generated by Django 2.0.8 on 2019-10-14 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
                ('sobrenome', models.CharField(max_length=20)),
            ],
            options={
                'db_table': '"design"."cliente"',
            },
        ),
        migrations.CreateModel(
            name='profissional',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
                ('sobrenome', models.CharField(max_length=20)),
            ],
            options={
                'db_table': '"design"."profissional"',
            },
        ),
        migrations.CreateModel(
            name='secao_marcada',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('data_secao', models.DateTimeField()),
                ('cliente_nome', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clients_design.cliente')),
                ('profissional_nome', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clients_design.profissional')),
            ],
            options={
                'db_table': '"design"."secao"',
            },
        ),
    ]
