# Generated by Django 2.0.8 on 2019-10-18 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('sobrenome', models.CharField(max_length=20)),
            ],
            options={
                'db_table': '"design"."cliente"',
            },
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('sobrenome', models.CharField(max_length=20)),
            ],
            options={
                'db_table': '"design"."profissional"',
            },
        ),
        migrations.CreateModel(
            name='SecaoMarcada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_secao', models.DateTimeField()),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clients_design.Cliente')),
                ('profissional_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clients_design.Profissional')),
            ],
            options={
                'db_table': '"design"."secao"',
            },
        ),
    ]
