# Generated by Django 2.0.8 on 2019-10-19 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients_design', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItensConsumidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
            ],
            options={
                'db_table': '"design"."itensconsumidos"',
            },
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=100)),
                ('preco', models.IntegerField()),
            ],
            options={
                'db_table': '"design"."produtos"',
            },
        ),
        migrations.AddField(
            model_name='itensconsumidos',
            name='produto_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clients_design.Produtos'),
        ),
        migrations.AddField(
            model_name='itensconsumidos',
            name='secao_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clients_design.SecaoMarcada'),
        ),
    ]
